### ISSUE TITLE
result of package "shadow" not reproducible

### ISSUE THREAD

**Issue by olafhering** [janestreet/ocaml-compiler-libs#6]
A rebuild of unchanged sources results in different binaries in the `shadow` package.

It looks like this is the culprit:
````src/shadow/gen/gen.ml:15:  let files = Sys.readdir dir |> Array.to_list in````

The result of `readdir()` is not stable. I think the list must be sorted prior further processing.

**Comment by greedy** [comment]
I ran into this problem too and filed #8 without checking for an existing issue first. Anyway, I've actually encountered build failures relating to this when using nix and getting cached binaries built from different hosts as detailed in #8.

**Comment by ghost** [comment]
Looks like we are missing a `List.sort`

**Comment by ghost** [comment]
I pushed a fix to master. If you can confirm that it fully fixes the issue you are observing we'll submit a new release to the opam repo.

**Comment by olafhering** [comment]
I came up with this patch a few months ago, which fixed it for me:

````patch
--- a/src/shadow/gen/gen.ml
+++ b/src/shadow/gen/gen.ml
@@ -12,7 +12,7 @@ let () =
       failwith "bad command line arguments"
   in
 
-  let files = Sys.readdir dir |> Array.to_list in
+  let files = Sys.readdir dir |> Array.to_list |> List.sort ~cmp:String.compare in
 
   let all_exposed_modules =
     List.filter files ~f:(fun fn -> Filename.check_suffix fn ".cmi")
````
So yes, thanks for doing commit 5d2f8865ddef5aea453d5d72d31ff7a9b5105977.

**Comment by ghost** [comment]
Alright, new release submitted: https://github.com/ocaml/opam-repository/pull/19314
