### ISSUE TITLE
Deprecation warning shows wrong module name

### ISSUE THREAD

**Issue by emillon** [janestreet/ocaml-compiler-libs#7]
Hi,
When refering to a toplevel compiler-libs module, the deprecation warning refers to `Ocamlcommon`:

```
83 |   module M = Ppxlib.Printast
                  ^^^^^^^^^^^^^^^
Error (alert deprecated): module Ppxlib.Printast
Accessing this module directly is deprecated, use Ocamlcommon.Printast instead
```

But the actual module name is `Ocaml_common`.

Thanks!

**Comment by ghost** [comment]
Indeed, fixed in master

**Comment by ghost** [comment]
released submitted: https://github.com/ocaml/opam-repository/pull/17241
